### ISSUE TITLE
Performance Requirements not met in Preprod

### ISSUE THREAD

**Issue by iwootten** [ONSdigital/sdx-collect#107]
Currently, non functional requirements within the pre-production environment are not met. Originally, we stated that 100 surveys should be processed within a minute. Under our development environment, this is true (we can do around 150) - however on preprod, we can only process about 20.

The bottleneck is due to the length of time it takes for FTP login (approx 1s) and that a single survey transform reopens connections for each file it needs to deliver over ftp. As we're transferring 4 files, this means submission of a single survey takes 4.5s, where 4s is waiting for ftp login.

A quick win seems to be sending all files we create for a submission in one go, or ideally holding a persistent ftp connection open and sending all files across that.

**Comment by necrophonic** [comment]
We're now persisting connections and have improved performance to roughly 2 surveys per second (~120 per minute)

**Comment by iwootten** [comment]
Amused that this has been resolved over a year later!
