### ISSUE TITLE
Multiple image files getting generated when receipting service is offline or doesn't know about the user

### ISSUE THREAD

**Issue by yoganandkunche** [ONSdigital/sdx-collect#136]
**Expected behaviour**
SDX must only generate one image file

**Actual behaviour**
SDX is generated 3 image files

**Steps to reproduce the behaviour**
launch a 0112 survey from https://preprod-surveys.eq.ons.digital/dev link
complete the survey and submit
look in Filezilla for the image files gnerated

**Screenshot**

**Comment by collisdigital** [comment]
@yoganandkunche can you check the impact on the downstream processing of this defect?

**Comment by yoganandkunche** [comment]
@collisdigital This issue is not present in pre-prod or prod when launched from RRM. This is an issue only when you launch the survey from https://preprod-surveys.eq.ons.digital/dev 
I checked with downstream (@Martyn Colmer) about the impact if it happens in prod and he thinks it not a good thing as it will be listed 3 times as they will have different scan numbers.

**Comment by eldeal** [comment]
This issue was caused by collect processing to downstream regardless of a failure to receipt, and retrying. This has been resolved by refactoring receipting to a separate service https://github.com/ONSdigital/sdx-collect/commit/a3d43349e6baa0d9a0ff8bc6b973017a1da3824e
