### ISSUE TITLE
Stop logging body

### ISSUE THREAD

**Issue by necrophonic** [ONSdigital/sdx-collect#144]
No need to log encrypted body - gets truncated anyhow so is now un-decryptable from the log

**Comment by eldeal** [comment]
Was this issue resolved in this commit (https://github.com/ONSdigital/sdx-collect/commit/b935bc46f4604b824107f372b0822fa6be3b3a5f) or are there other occurrences?

**Comment by necrophonic** [comment]
Yeah looks like it was. Guess the issue just wasn't referenced.
